name: MacRDP
on: 
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:                 
    - name: Enabling Remote Access
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
          curl -s -o start.sh -L "https://raw.githubusercontent.com/JohnnyNetsec/github-vm/main/mac/start.sh"
          chmod +x start.sh
          bash start.sh "$NGROK_AUTH_TOKEN"
          
    - name: Log In Details To VNC Server
      run: |
         curl -s -o start.sh -L "https://raw.githubusercontent.com/JohnnyNetsec/github-vm/main/mac/login.sh"
         chmod +x login.sh
         bash login.sh
         sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
         -activate -configure -access -on \
         -restart -agent -privs -all
         sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
         
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
